package com.badlogic.mario.Enemys;

public enum EnemyType {
    TARTARUGA_VERDE_L,
    TARTARUGA_VERMELHA_L,
    TARTARUGA_AZUL_L,
    TARTARUGA_VERDE_R,
    TARTARUGA_VERMELHA_R,
    TARTARUGA_AZUL_R,
    TARTARUGA_VOADORA_VERDE_L,
    TARTARUGA_VOADORA_VERMELHA_L,
    TARTARUGA_VOADORA_AZUL_L,
    TARTARUGA_VOADORA_VERDE_R,
    TARTARUGA_VOADORA_VERMELHA_R,
    TARTARUGA_VOADORA_AZUL_R,
    BICHO_MARROM_L,
    BICHO_AZUL_L,
    BICHO_BRANCO_L,
    BICHO_MARROM_R,
    BICHO_AZUL_R,
    BICHO_BRANCO_R,
}
